"""Modularity / scalability health lens — pure stdlib ``ast``, zero-dep, never-raise.

renmark enforces modularity at *plan time* (one-file-per-task) but never
*measures* it on the shipped codebase. This module is the missing measurement
layer: an ADVISORY, deterministic, zero-LLM, stdlib-``ast``-only analyzer that
surfaces code-health gaps through ``init``'s existing standards-health pipeline.

Its findings are reported via the SAME :class:`renmark.init.Gap` shape the
standards-health detectors emit, so they render in ``dev-standards.md`` and count
toward the ``HEALTH:`` stdout line. They are **advisory only** — they never block
the pipeline and never trigger an auto-refactor.

The 5 metrics, each with a ``warn`` and a ``major`` band (tunable module
constants below):

1. **module LOC** (code lines — blanks / comments / docstring lines excluded):
   :data:`MODULE_LOC_WARN` / :data:`MODULE_LOC_MAJOR`.
2. **function / method length** in code LOC (per ``FunctionDef`` /
   ``AsyncFunctionDef``): :data:`FUNC_LOC_WARN` / :data:`FUNC_LOC_MAJOR`.
3. **cyclomatic branch count** per function (``if`` / ``for`` / ``while`` /
   ``except`` / ``with`` / boolean-op / comprehension-``if`` / ``match`` case,
   plus one): :data:`CYCLO_WARN` / :data:`CYCLO_MAJOR`.
4. **import fan-out** per module (``import`` / ``from ... import`` statements;
   ``__init__.py`` excluded — re-exports): :data:`FANOUT_WARN` / :data:`FANOUT_MAJOR`.
5. **cognitive complexity** per function (nesting-weighted: each branching
   construct adds ``1 + current_nesting_level``): :data:`COGNITIVE_WARN` /
   :data:`COGNITIVE_MAJOR`.

Design contract (mirrors :mod:`renmark.sizing`):

- ``analyze(repo)`` is a pure function of the filesystem; it never mutates state.
- **Never raises into the caller.** Every walk / read / ``ast.parse`` is wrapped;
  a syntax-error or otherwise unparseable file is SKIPPED and analysis continues.
  On any unexpected failure the result degrades to ``[]`` (no gaps reported) —
  the same safe posture as ``sizing.py``.
- Every threshold is a documented, tunable module-level constant.

False-positive suppression (mandatory): files under a ``tests/`` or
``__tests__/`` directory are skipped (``test/`` singular is NOT — it's a common
production package name); generated files whose ``@generated`` / "do not edit"
marker appears on a COMMENT-ONLY line near the top are skipped (a docstring or
prose mention does NOT suppress);
``__init__.py`` is excluded from the fan-out metric; class-level field
assignments (dataclass / Enum bodies) are not counted as branches or cognitive
complexity. Code lines are counted, never raw lines.
"""

from __future__ import annotations

import ast
from pathlib import Path

from .init import Gap, _is_excluded

# ── Thresholds (tunable) ─────────────────────────────────────────────────────

#: Module LOC (code lines): pylint ``max-module-lines`` default is 1000.
MODULE_LOC_WARN: int = 500
MODULE_LOC_MAJOR: int = 1000

#: Function / method length in code LOC.
FUNC_LOC_WARN: int = 50
FUNC_LOC_MAJOR: int = 100

#: Cyclomatic branch count per function (mccabe-style: decision points + 1).
CYCLO_WARN: int = 10
CYCLO_MAJOR: int = 20

#: Import fan-out per module (``import`` + ``from`` statements). ``__init__.py``
#: is excluded from this metric (re-export hubs legitimately import a lot).
FANOUT_WARN: int = 15
FANOUT_MAJOR: int = 25

#: Cognitive complexity per function (SonarQube-style nesting-weighted).
COGNITIVE_WARN: int = 15
COGNITIVE_MAJOR: int = 30

# ── Suppression signals (tunable) ────────────────────────────────────────────

#: Path components that mark a test tree — files under a directory with one of
#: these EXACT names are skipped. Note ``"test"`` (singular) is intentionally
#: NOT included: ``src/test/...`` is a common production package name, not a test
#: tree, and suppressing it would hide real code.
TEST_PATH_PARTS: frozenset[str] = frozenset({"tests", "__tests__"})

#: Marker substrings (checked case-insensitively) that mark a machine-generated
#: file. To avoid false-negatives, these are matched ONLY against comment-only
#: lines (a physical line whose stripped text starts with ``#``) near the top of
#: the file — NEVER against docstrings, string literals, or prose. A hand-written
#: module that merely *mentions* "generated by" in its docstring is therefore
#: still analyzed and flagged; a real ``# Code generated by ...`` comment header
#: is suppressed.
GENERATED_MARKERS: tuple[str, ...] = (
    "@generated",
    "do not edit",
    "do not modify",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by",
    "this file is generated",
    "code generated",
)

#: How many leading lines to scan for a generated-file marker.
GENERATED_SCAN_LINES: int = 40


# ── Public API ────────────────────────────────────────────────────────────────


def analyze(repo: Path | str) -> list[Gap]:
    """Analyze every Python source file under ``repo`` and return advisory gaps.

    Walks Python files (reusing ``init``'s exclusion set), parses each with
    :func:`ast.parse` inside a try/except — a syntax-error or any per-file
    failure SKIPS that file and continues. For each file the 5 modularity
    metrics are computed and one :class:`~renmark.init.Gap` is emitted per
    threshold breach, ``severity`` set to ``"warn"`` (warn band) or ``"danger"``
    (major band).

    Never raises: any unexpected error degrades to ``[]`` (no gaps reported),
    matching :mod:`renmark.sizing`'s safety posture.
    """
    try:
        repo_path = Path(repo)
        gaps: list[Gap] = []
        for file in _walk_python_files(repo_path):
            try:
                gaps.extend(_analyze_file(file, repo_path))
            except Exception:  # one bad file must never sink the whole scan
                continue
        # warn band is "warn"; major band is "danger" — sort danger first.
        order = {"danger": 0, "warn": 1, "info": 2}
        gaps.sort(key=lambda g: order.get(g.severity, 99))
        return gaps
    except Exception:  # never raise into the caller; degrade to no gaps.
        return []


# ── File discovery ─────────────────────────────────────────────────────────────


def _walk_python_files(repo: Path) -> list[Path]:
    """Return Python source files under ``repo``, excluding ``init``'s noise dirs.

    Reuses :func:`renmark.init._is_excluded` so the walker matches the rest of
    the toolchain (``.git``, ``node_modules``, ``.venv``, renmark runtime, …).
    Never raises — an unreadable tree degrades to whatever was collected so far.
    """
    out: list[Path] = []
    try:
        for path in repo.rglob("*.py"):
            try:
                if not path.is_file():
                    continue
                if _is_excluded(path, repo):
                    continue
            except OSError:
                continue
            out.append(path)
    except OSError:
        return out
    return out


def _rel(path: Path, repo: Path) -> str:
    """Repo-relative POSIX path string for human-readable messages."""
    try:
        return str(path.relative_to(repo)).replace("\\", "/")
    except ValueError:
        return path.name


# ── Suppression predicates ─────────────────────────────────────────────────────


def _is_under_tests(path: Path, repo: Path) -> bool:
    """True if any path component (relative to repo) is a test-tree directory."""
    try:
        parts = path.relative_to(repo).parts
    except ValueError:
        parts = path.parts
    # The file's own name isn't a "directory"; check the parent components.
    return any(p in TEST_PATH_PARTS for p in parts[:-1])


def _is_generated(text: str) -> bool:
    """True if a leading COMMENT-ONLY line carries a machine-generated marker.

    Only physical lines whose stripped text starts with ``#`` (i.e. genuine
    Python comments, including shebang-style banner headers) are inspected. A
    marker phrase that appears inside a module docstring, a string literal, or
    ordinary prose does NOT suppress the file — that was the source of a verified
    false-negative where a hand-written module mentioning "generated by" in its
    docstring returned zero gaps. Real generators emit their banner as a comment.
    """
    for raw in text.splitlines()[:GENERATED_SCAN_LINES]:
        stripped = raw.strip()
        if not stripped.startswith("#"):
            continue
        comment = stripped.lower()
        if any(marker in comment for marker in GENERATED_MARKERS):
            return True
    return False


# ── Per-file analysis ───────────────────────────────────────────────────────────


def _analyze_file(path: Path, repo: Path) -> list[Gap]:
    """Compute all 5 metrics for one file and return one Gap per breach.

    Returns ``[]`` (file skipped) on read failure, syntax error, a test-tree
    path, or a generated-file marker. Never raises.
    """
    if _is_under_tests(path, repo):
        return []
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    if _is_generated(text):
        return []
    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError, RecursionError):
        return []
    except Exception:
        return []

    rel = _rel(path, repo)
    gaps: list[Gap] = []

    # 1. module LOC (code lines)
    code_lines = _module_code_lines(text, tree)
    gaps.extend(_module_loc_gap(rel, code_lines))

    # 4. import fan-out (skip __init__.py — re-export hubs)
    if path.name != "__init__.py":
        fan_out = _import_fan_out(tree)
        gaps.extend(_fan_out_gap(rel, fan_out))

    # 2, 3, 5. per-function metrics
    for func in _iter_functions(tree):
        qual = _func_label(func)
        func_loc = _func_code_lines(func, text)
        gaps.extend(_func_loc_gap(rel, qual, func_loc))
        gaps.extend(_cyclomatic_gap(rel, qual, _cyclomatic(func)))
        gaps.extend(_cognitive_gap(rel, qual, _cognitive(func)))

    return gaps


# ── Metric 1: module code lines ────────────────────────────────────────────────


def _module_code_lines(text: str, tree: ast.Module) -> int:
    """Count code lines: exclude blank lines, comment lines, and docstring lines.

    Docstring line numbers (module-, class-, and function-level) are gathered
    from the AST and subtracted; blank and ``#``-comment physical lines are
    excluded by inspecting the source text.
    """
    docstring_lines = _docstring_line_numbers(tree)
    count = 0
    for lineno, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if lineno in docstring_lines:
            continue
        count += 1
    return count


def _docstring_line_numbers(tree: ast.Module) -> set[int]:
    """Physical line numbers occupied by module / class / function docstrings."""
    lines: set[int] = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        doc = ast.get_docstring(node, clean=False)
        if doc is None:
            continue
        body = getattr(node, "body", None)
        if not body:
            continue
        expr = body[0]
        if not isinstance(expr, ast.Expr):
            continue
        const = expr.value
        if not isinstance(const, ast.Constant) or not isinstance(const.value, str):
            continue
        start = getattr(const, "lineno", None)
        end = getattr(const, "end_lineno", start)
        if start is None:
            continue
        if end is None:
            end = start
        lines.update(range(start, end + 1))
    return lines


# ── Metric 2: function code lines ───────────────────────────────────────────────


def _func_code_lines(func: ast.FunctionDef | ast.AsyncFunctionDef, text: str) -> int:
    """Code lines OWNED by a function — its signature + body, nested defs excluded.

    Spans the function's own start (its first decorator line if decorated, else
    its ``def``/``async def`` line) through its ``end_lineno``, so the signature
    and decorators are counted. Blank lines, ``#``-comment lines, and the
    function's own docstring lines are excluded. Line-spans owned by NESTED
    ``FunctionDef`` / ``AsyncFunctionDef`` / ``ClassDef`` (including their own
    decorators) are subtracted so each function owns exactly its own LOC — no
    undercount (signature dropped) and no double-count (nested bodies swallowed).
    """
    if not func.body:
        return 0
    start = _node_start_line(func)
    end = getattr(func, "end_lineno", start) or start

    excluded: set[int] = set()

    # Subtract every nested function/class definition's full line-span so its
    # lines are attributed to that nested node, not to this function.
    for child in ast.walk(func):
        if child is func:
            continue
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            c_start = _node_start_line(child)
            c_end = getattr(child, "end_lineno", c_start) or c_start
            excluded.update(range(c_start, c_end + 1))

    # Subtract this function's own docstring lines.
    first = func.body[0]
    doc = ast.get_docstring(func, clean=False)
    if doc is not None and isinstance(first, ast.Expr):
        const = first.value
        if isinstance(const, ast.Constant) and isinstance(const.value, str):
            d_start = getattr(const, "lineno", start)
            d_end = getattr(const, "end_lineno", d_start) or d_start
            excluded.update(range(d_start, d_end + 1))

    all_lines = text.splitlines()
    count = 0
    for lineno in range(start, end + 1):
        if lineno in excluded:
            continue
        if lineno - 1 < 0 or lineno - 1 >= len(all_lines):
            continue
        stripped = all_lines[lineno - 1].strip()
        if not stripped or stripped.startswith("#"):
            continue
        count += 1
    return count


def _node_start_line(node: ast.AST) -> int:
    """First physical line a def/class owns — its first decorator, else its own line.

    A decorated definition's ``lineno`` points at the ``def``/``class`` keyword,
    not the ``@decorator`` lines above it, so we walk the decorator list to find
    the true top of the construct.
    """
    own = getattr(node, "lineno", 1)
    decorators = getattr(node, "decorator_list", None) or []
    starts = [own]
    for dec in decorators:
        d_line = getattr(dec, "lineno", None)
        if d_line is not None:
            starts.append(d_line)
    return min(starts)


# ── Metric 4: import fan-out ────────────────────────────────────────────────────


def _import_fan_out(tree: ast.Module) -> int:
    """Count ``Import`` / ``ImportFrom`` statements anywhere in the module."""
    return sum(1 for node in ast.walk(tree) if isinstance(node, (ast.Import, ast.ImportFrom)))


# ── Function iteration ──────────────────────────────────────────────────────────


def _iter_functions(tree: ast.Module) -> list[ast.FunctionDef | ast.AsyncFunctionDef]:
    """All function/method defs in the module (nested ones included)."""
    return [n for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]


def _func_label(func: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Function name plus its measured value placeholder, e.g. ``my_func``."""
    return f"{func.name}()"


# ── Metric 3: cyclomatic complexity ─────────────────────────────────────────────


def _cyclomatic(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    """McCabe-style branch count: decision nodes within the function body + 1.

    Counts ``If`` / ``For`` / ``While`` / ``ExceptHandler`` / ``With`` /
    ``BoolOp`` (and/or) / comprehension-``if`` / ``match`` ``case`` nodes that
    belong to THIS function (nested functions are excluded — they have their own
    score). Class-level field assignments inside the function are not branches.
    """
    count = 1
    for node in _walk_own_body(func):
        if isinstance(
            node,
            (ast.If, ast.For, ast.AsyncFor, ast.While, ast.ExceptHandler, ast.With, ast.AsyncWith),
        ):
            count += 1
        elif isinstance(node, ast.BoolOp):
            # n operands → n-1 additional branch decisions.
            count += max(len(node.values) - 1, 1)
        elif isinstance(node, ast.comprehension):
            count += len(node.ifs)
        elif _is_match_case(node):
            count += 1
    return count


# ── Metric 5: cognitive complexity ──────────────────────────────────────────────


def _cognitive(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    """Nesting-weighted cognitive complexity (SonarQube-style approximation).

    Each branching construct adds ``1 + current_nesting_level``; nesting
    increments inside ``if`` / ``for`` / ``while`` / ``with`` / ``except``
    bodies. A boolean operator adds one per logical branch in its operand chain
    (``len(values) - 1``), so a longer ``and``/``or`` chain scores higher than a
    short one. Comprehension ``if``s add a flat increment per ``if``. Nested
    function definitions are not descended into (they score separately).
    """
    score = 0

    def visit(node: ast.AST, nesting: int) -> None:
        nonlocal score
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue  # nested functions scored on their own
            is_nesting_construct = isinstance(
                child,
                (ast.If, ast.For, ast.AsyncFor, ast.While, ast.With, ast.AsyncWith, ast.ExceptHandler),
            ) or _is_match_case(child)
            if is_nesting_construct:
                score += 1 + nesting
                visit(child, nesting + 1)
            elif isinstance(child, ast.BoolOp):
                # n operands → n-1 logical branches; a longer chain scores higher.
                score += max(len(child.values) - 1, 1)
                visit(child, nesting)
            elif isinstance(child, ast.comprehension):
                score += len(child.ifs)
                visit(child, nesting)
            else:
                visit(child, nesting)

    visit(func, 0)
    return score


# ── AST traversal helpers ───────────────────────────────────────────────────────


def _walk_own_body(func: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.AST]:
    """All descendant nodes of ``func`` EXCLUDING nested function bodies.

    A nested ``def``/``async def`` carries its own complexity score, so we don't
    let its internals inflate the enclosing function's count.
    """
    out: list[ast.AST] = []

    def walk(node: ast.AST) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            out.append(child)
            walk(child)

    walk(func)
    return out


def _is_match_case(node: ast.AST) -> bool:
    """True if ``node`` is a ``match`` ``case`` clause (Python 3.10+ ``match_case``)."""
    match_case = getattr(ast, "match_case", None)
    return match_case is not None and isinstance(node, match_case)


# ── Gap construction (per metric) ───────────────────────────────────────────────


def _band(value: int, warn: int, major: int) -> str | None:
    """Return ``"danger"`` (>= major), ``"warn"`` (>= warn), or ``None`` (ok)."""
    if value >= major:
        return "danger"
    if value >= warn:
        return "warn"
    return None


def _module_loc_gap(rel: str, code_lines: int) -> list[Gap]:
    band = _band(code_lines, MODULE_LOC_WARN, MODULE_LOC_MAJOR)
    if band is None:
        return []
    limit = MODULE_LOC_MAJOR if band == "danger" else MODULE_LOC_WARN
    return [
        Gap(
            band,
            f"Oversized module: `{rel}` ({code_lines} code lines)",
            f"`{rel}` has {code_lines} code lines (threshold {limit}). Large modules are "
            "hard to navigate, review, and test, and tend to accrete unrelated responsibilities.",
            f"Split `{rel}` into focused modules along its natural seams "
            "(one cohesive responsibility per file). Advisory — never auto-refactored.",
        )
    ]


def _fan_out_gap(rel: str, fan_out: int) -> list[Gap]:
    band = _band(fan_out, FANOUT_WARN, FANOUT_MAJOR)
    if band is None:
        return []
    limit = FANOUT_MAJOR if band == "danger" else FANOUT_WARN
    return [
        Gap(
            band,
            f"High import fan-out: `{rel}` ({fan_out} imports)",
            f"`{rel}` has {fan_out} import statements (threshold {limit}). High fan-out signals "
            "a module coupled to many others — a change-amplifier and a refactoring hazard.",
            f"Reduce coupling in `{rel}`: extract a narrower interface, group related imports "
            "behind a facade, or move logic closer to its dependencies. Advisory.",
        )
    ]


def _func_loc_gap(rel: str, qual: str, func_loc: int) -> list[Gap]:
    band = _band(func_loc, FUNC_LOC_WARN, FUNC_LOC_MAJOR)
    if band is None:
        return []
    limit = FUNC_LOC_MAJOR if band == "danger" else FUNC_LOC_WARN
    return [
        Gap(
            band,
            f"Long function: `{rel}` → `{qual}` ({func_loc} code lines)",
            f"`{qual}` in `{rel}` spans {func_loc} code lines (threshold {limit}). Long functions "
            "are hard to read in one pass and usually do more than one thing.",
            f"Extract cohesive blocks of `{qual}` into well-named helpers. Advisory.",
        )
    ]


def _cyclomatic_gap(rel: str, qual: str, value: int) -> list[Gap]:
    band = _band(value, CYCLO_WARN, CYCLO_MAJOR)
    if band is None:
        return []
    limit = CYCLO_MAJOR if band == "danger" else CYCLO_WARN
    return [
        Gap(
            band,
            f"High cyclomatic complexity: `{rel}` → `{qual}` ({value} branches)",
            f"`{qual}` in `{rel}` has a cyclomatic branch count of {value} (threshold {limit}). "
            "Many decision points mean many paths to test and many ways to be wrong.",
            f"Reduce branching in `{qual}`: early returns, guard clauses, table/dispatch dictionaries, "
            "or splitting the function. Advisory.",
        )
    ]


def _cognitive_gap(rel: str, qual: str, value: int) -> list[Gap]:
    band = _band(value, COGNITIVE_WARN, COGNITIVE_MAJOR)
    if band is None:
        return []
    limit = COGNITIVE_MAJOR if band == "danger" else COGNITIVE_WARN
    return [
        Gap(
            band,
            f"High cognitive complexity: `{rel}` → `{qual}` (score {value})",
            f"`{qual}` in `{rel}` has a nesting-weighted cognitive-complexity score of {value} "
            f"(threshold {limit}). Deep nesting is disproportionately hard for a human to follow.",
            f"Flatten nesting in `{qual}`: invert conditions to return early, extract nested blocks "
            "into helpers, and reduce branching depth. Advisory.",
        )
    ]
